### ISSUE TITLE
Any plan to update to magisk-v28?

### ISSUE THREAD

**Issue by Mark-Joy** [1q23lyc45/KitsuneMagisk#6]
Hello,

Thank you so much for the new fork!
Do you have any plan to update to magisk-v28?

**Comment by 1q23lyc45** [comment]
I'm also planning to upgrade to Magisk v28, but I'm afraid I'm having a lot of trouble with it. I'm trying to merge https://github.com/1q23lyc45/Magisk/commit/6d79de7d7191bce888bbb6a4cea25a1178cf74c0 , but I've run into a big conflict and now I can't compile it successfully.
This upgrade can take a long time to complete, so please wait a few months.
Thank you for your patience and understanding!

**Comment by 1q23lyc45** [comment]
I'm so sorry I can't complete the update. Because there are too many conflicts to be resolved. So the project will stay in version 27.2.
I'll add action.sh features, if possible.

**Comment by BadIDMan** [comment]
It would be nice if you also fixed the modules presentation issue when built-in Zygisk is disabled.
When built-in Zygisk is not enabled and Zygisk Next module is handling zygisk, you may see the following in the module:
![image](https://github.com/user-attachments/assets/377434fb-2623-4495-88b3-688cf2e17a99)

which misleads people into thinking they don't have zygisk.

**Comment by 1q23lyc45** [comment]
Thank you so much for your feedback!
You can try, uninstall ZygiskNext, and then install this module https://github.com/PerformanC/ReZygisk/releases/download/v1.0.0-rc.1/ReZygisk-v1.0.0-rc.1-release.zip

The developers of ReZygisk have adapted Kitsune Mask separately and should be perfectly compatible. 
Also, update version 27.2. I think you're probably using the version I released a week ago. https://github.com/1q23lyc45/KitsuneMagisk/releases/download/v27.2-kitsune-1/app-release.apk

**Comment by 1q23lyc45** [comment]
Action.sh support implementation has been added and is already included in the v27.2-kitsune-2 release. Now you can update.

**Comment by snakechilds** [comment]
thanks! can this magisk use integrity wizard on emulator ? i want to pass play integrity

**Comment by 1q23lyc45** [comment]
> thanks! can this magisk use integrity wizard on emulator ? i want to pass play integrity

Yes, of course. You can use https://github.com/chiteroman/PlayIntegrityFix .
It is recommended to use it on Android 9 (or above) emulators, because the current version has issues with Android 7 support (28c403c1bc8b0b691806d08fdfbee7357cb11bb2 This commit breaks support for Android 7)

**Comment by snakechilds** [comment]
the issue is, we cant install shamiko in this magisk

**Comment by BadIDMan** [comment]
> the issue is, we cant install shamiko in this magisk

Shamiko is not needed with Kitsune Mask.

**Comment by BadIDMan** [comment]
> Thank you so much for your feedback! You can try, uninstall ZygiskNext, and then install this module https://github.com/PerformanC/ReZygisk/releases/download/v1.0.0-rc.1/ReZygisk-v1.0.0-rc.1-release.zip
> 
> The developers of ReZygisk have adapted Kitsune Mask separately and should be perfectly compatible. Also, update version 27.2. I think you're probably using the version I released 2 weeks ago. https://github.com/1q23lyc45/KitsuneMagisk/releases/download/v27.2-kitsune-1/app-release.apk

ReZygisk is not hiding Zygisk as effective as Zygisk Next.
Look here: https://xdaforums.com/t/how-to-bypass-microsoft-intune-company-portal-root-checks-working-as-of-september-2024.4663331/page-6#post-89862925
I'm back using Zygisk Next.

**Comment by snakechilds** [comment]
> > the issue is, we cant install shamiko in this magisk
> 
> Shamiko is not needed with Kitsune Mask.

did you pass play integrity on emulator ?

**Comment by 1q23lyc45** [comment]
I know that Shamiko and Zygisknext can't be used, but without their source code, adaptation is impossible. It's like trying to extract gold from iron ore. It's not a problem with the Kitsune Mask, it's the lack of the necessary source material.

**Comment by 1q23lyc45** [comment]
> > > the issue is, we cant install shamiko in this magisk
> > 
> > 
> > Shamiko is not needed with Kitsune Mask.
> 
> did you pass play integrity on emulator ?

Android 9 emulator does, but Android 7 cannot.

**Comment by snakechilds** [comment]
thanks! 
Can i get your telegram id ?

**Comment by 1q23lyc45** [comment]
> thanks! Can i get your telegram id ?

Sorry, but I have no Telegram.

**Comment by MIkeeJY** [comment]
> Hello,
> 
> Thank you so much for the new fork! Do you have any plan to update to magisk-v28?

If you wanna use  magisk-v28, you'd better use magisk alpha instead of kitsune~

**Comment by snakechilds** [comment]
> > > > > the issue is, we cant install shamiko in this magisk
> 
> > > > 
> 
> > > > 
> 
> > > > Shamiko is not needed with Kitsune Mask.
> 
> > > 
> 
> > > 
> 
> > > did you pass play integrity on emulator ?
> 
> > 
> 
> > Android 9 emulator does, but Android 7 cannot.
> 
> 
> 
> in which emulator were you able to pass the play Integrity?
> 
> memu, nox, Android Studio?

No one can pass it, because emulator compeletely different. i think he misunderstand my comment

**Comment by MIkeeJY** [comment]
> > > > > the issue is, we cant install shamiko in this magisk
> > > > 
> > > > 
> > > > Shamiko is not needed with Kitsune Mask.
> > > 
> > > 
> > > did you pass play integrity on emulator ?
> > 
> > 
> > Android 9 emulator does, but Android 7 cannot.
> 
> in which emulator were you able to pass the play Integrity? memu, nox, Android Studio?

No one can pass it,PI detection requires hardware parameters and the support of various sensors, which are missing in the simulator

**Comment by 1q23lyc45** [comment]
> > > > > the issue is, we cant install shamiko in this magisk
> > > > 
> > > > 
> > > > Shamiko is not needed with Kitsune Mask.
> > > 
> > > 
> > > did you pass play integrity on emulator ?
> > 
> > 
> > Android 9 emulator does, but Android 7 cannot.
> 
> in which emulator were you able to pass the play Integrity? memu, nox, Android Studio?

VPhoneGaga Latest Android 10 or AVD Android 9+

Install the PlayIntegrityFix module and you'll be able to pass the play Integrity. https://github.com/chiteroman/PlayIntegrityFix/releases/download/v18.2/PlayIntegrityFix_v18.2.zip

**Comment by 1q23lyc45** [comment]
> > Hello,
> > Thank you so much for the new fork! Do you have any plan to update to magisk-v28?
> 
> If you wanna use magisk-v28, you'd better use magisk alpha instead of kitsune~

The latest version of Magisk Alpha is only 24101, that is, v24.1, and it hasn't been updated for two years, are you sure you can accept it? It's weird to be able to use it.
See for yourself. And it's only a fork version, and the official developers have run away.
https://github.com/CrackerCat/magisk-alpha/blob/alpha/gradle.properties

**Comment by 1q23lyc45** [comment]
## **Announcement**

1. Because Magisk has refactored so much this year, it is very difficult to upgrade to the latest version. Even if the conflict is resolved, the compilation is difficult to complete. This is a technical issue that can't be solved, so I don't have any way to upgrade to the new version of Magisk. New features can only be added selectively.
2. If you want any functionality, please open a separate issue.
3. If you have any questions about Zygisk Next, please report them to the developers of Zygisk Next and don't come to me. I can't fix it. Or use NeoZygisk/ReZygisk.
4. **Don't install Shamiko.** If you still choose to use it, we will not provide any support and will not be held responsible.

**Comment by BadIDMan** [comment]
> ## **Announcement**
> 
>     3. If you have any questions about Zygisk Next, please report them to the developers of Zygisk Next and don't come to me. I can't fix it. Please use NeoZygisk or ReZygisk.

Unfortunately Zygisk Next won't be adjusted to correctly present modules in your Kitsune fork:
https://github.com/Dr-TSNG/ZygiskNext/issues/190
:-(

**Comment by MIkeeJY** [comment]
@BadIDMan Hi man,but Rezygisk can,try  https://github.com/PerformanC/ReZygisk/actions/runs/11998540660

**Comment by BadIDMan** [comment]
> @BadIDMan Hi man,but Rezygisk can work fine,try https://github.com/PerformanC/ReZygisk/actions/runs/11998540660
If you had scrolled up and read one of my posts, you would not have recommended ReZygisk to me

**Comment by 1q23lyc45** [comment]
> > @BadIDMan Hi man,but Rezygisk can work fine,try https://github.com/PerformanC/ReZygisk/actions/runs/11998540660
> If you had scrolled up and read one of my posts, you would not have recommended ReZygisk to me

If you're not afraid of them (Zygisk Next developers) to remotely control your phone, you can go for it.
Read this: https://www.gnu.org/proprietary/proprietary.en.html

**Comment by 1q23lyc45** [comment]
You can review the code in this repository. I never blacklisted Zygisk Next, instead, it was the Zygisk Next developers who added my project to the blacklist.

**Comment by 1q23lyc45** [comment]
> > First of all, Shamiko is completely useless on the Kitsune Mask. Kitsune Mask already has Magisk Hide built-in. Zygisk Assistant is recommended. https://github.com/snake-4/Zygisk-Assistant/releases/download/v2.1.3/Zygisk-Assistant-v2.1.3-7b35d36-debug.zip
> > ...
> 
> Zygisk Assistant instructions say to disable Enforce DenyList in regular Magisk. Does that mean we are supposed to disable the oppositely corresponding Enforce SuList in Kitsune? Because if I do, I lose Kitsune's whitelist/allow-list mode, and it operates as blacklist/deny-list. (Apparently Zygisk Assistant doesn't "take over" the enforce function sufficiently to keep Kitsune in whitelist mode?)... If so, and how about MagiskHide?—are we supposed to disable that, too? (because it's labeled, "SuList is enforced")... Is there any way to keep Kitsune's distinctive whitelist mode with Zygisk Assistant (if Enforce SuList indeed has to be disabled)?

If you don't have special needs, you don't need to use Zygisk Assistant. It is enough to use MagiskHide directly. 
I've tested it, and using MagiskHide directly with hidden Magisk Manager can pass the detection of Hunter 6.0.3. 
(use this to hide bootloader unlock 
[hidebl.zip](https://github.com/user-attachments/files/18368073/hidebl.zip) )

**Comment by SchmyeBubbula** [comment]
Thanks for the advice!... But just in case I later turn-out to indeed have special needs, are you confirming that Kitsune can't operate in whitelist mode with Zygisk Assistant? (Enforce SuList disabled)

**Comment by 1q23lyc45** [comment]
> Thanks for the advice!... But just in case I later turn-out to indeed have special needs, are you confirming that Kitsune can't be made to operate in whitelist mode with Zygisk Assistant? (Enforce SuList disabled)

Sorry, I don't know about this either, you can test it yourself. ZygiskNext is known to work properly with blacklist mode. But it is generally not needed.
